---
title: "2/ 実習環境の構築"
modified-date: today
format: 
  revealjs:
    footer: "実習環境の構築"
metadata-files: 
  - "style/slide.yml"
---

```{r}
#| include: false
pacman::p_load(tidyverse)
```

{{< include _common.qmd >}}

# **1** 実習環境の概要

## 実習環境

以下のソフトウェア、ライブラリをなるべく最新版で用意

- R
- RStudio
- Quarto CLI
- {quarto}パッケージ
- （PDF出力をする場合）TeX環境（TeX Live、MacTeX、TinyTeXなど）

## ローカル環境とクラウド環境

- **ローカル環境**
   - 自分のPCにR/RStudio/Quarto CLI/TeX等をすべてインストール
   - 導入コスト（時間）はかかるが、クラウド環境より快適^[PCのスペックにもよる。]
   - 既存のRユーザーならこちらを推奨
- **クラウド環境**
   - R/RStudio/Quarto CLI/TeX一式が完備された環境（ネット接続必須）
   - 導入コストは非常に低いが、動作が重い
   - とりあえずQuartoと味わってみたいのであれば、これも$\bigcirc$

# **2** ローカル環境の場合

## RとRStudio

省略

## Quarto CLI

Quarto公式ホームページ（<https://quarto.org/>）から入手&インストール

- 「Get Started」メニュー、または以下のページから入手
   - <https://quarto.org/docs/download/>
- macOSの場合、homebrewからインストールも可
   - ターミナルで`brew install --cask quarto `

## {quarto}パッケージ

Rコンソールで以下のコマンドで{quarto}パッケージをインストール

```r
install.packages("quarto")
```

- インストールのみで十分（読み込みは不要）

## TeX環境

作成した文書、スライドをPDFフォーマットで出力したい場合

- すでに自分のPCにTeX環境が用意されている場合 $\Rightarrow$ 別途の設定は不要
   - 例）TeX Live（Windows/Unix/Linux）、MacTeX（macOS）
- TeXを使ったことがない or クラウド版（Overleafなど）のみ使用している場合
   - {tinytex}のインストールがおすすめ

```r
# {tinytexパッケージのインストール}
install.packages("tinytex")
# tinytexのインストール
tinytex::install_tinytex()
# 今は（多分）不要だが、念のために
tinytex::tlmgr_install("haranoaji")
```

# **3** クラウド環境の場合

## クラウド環境の種類

- [posit Cloud](https://posit.cloud/)
- [mybinder.org](https://mybinder.org/)
- [JDCat分析ツール](https://meatwiki.nii.ac.jp/confluence/spaces/jdcatanalysis/overview)

## posit Cloud

RStudioの開発元であるposit社が提供するクラウド版R & RStudio

- 無料版の制約（詳細は<https://posit.cloud/plans>）
   - [月間利用時間の上限]{.alert}あり（25時間）
   - スペックの制限（1GB RAM / 1CPU）
- 導入手順
   1. posit Cloud（<https://posit.cloud/>）のアカウント登録&ログイン
   1. 右のNew ProjectでNew RStudio Project
      - RStudioの設定は以下の設定を参照
      - <https://www.jaysong.net/RBook/r_customize.html>
         - Default working directoryは「/cloud/project」のままでOK
   1. 画面上段の「Untitled Project」をクリックし、プロジェクト名を指定
   1. {quarto}、{ragg}パッケージをインストールする

## mybinder.org

ウェブでRStudioが使えるサービス（事前登録不要）

- アカウントの概念が存在しないため、[アクセスする度にすべて初期化]{.alert}される。
   - 再現/再生用データ&コードの共有に適したサービス
   - とりあえず手軽にQuartoを味わっていみないのであればオススメ
- 次頁で紹介するJDCat分析ツールより劣るが、安定性は<i class="bi bi-hand-thumbs-up"></i>
- 起動方法
   - <https://mybinder.org/v2/gh/JaehyunSong/quarto_binder/HEAD> $\leftarrow$ クリック

## JDCat分析ツール

- mybinder.orgと同じサービスだが、継続的に使用可能なサービス
   - ただし、サーバーが不安定になることが多々ある
- 導入手順[（サーバーの立ち上げ）]{.small}
   1. Orthrosのホームーページでアカウント登録
      - <https://ui.orthros.gakunin.nii.ac.jp/>
      - [**必ず**]{.alert}`.ac.jp`、または`.go.jp`のメールアドレスを使うこと
   1. <https://binder.cs.rcos.nii.ac.jp/v2/gh/JaehyunSong/quarto_binder/HEAD>
   1. 所属機関を「Orthros」とし、ログインする。
   1. 数分待てばOK
- 立ち上げたサーバーの起動[（再利用）]{.small}
   1. <https://jupyter.cs.rcos.nii.ac.jp/>
   1. 所属機関を「Orthros」とし、ログインする。
   1. 表示されているURLをクリックする
      - URLが表示されていない場合、右の「Start」をクリック

# **4** プロジェクトの作成

## プロジェクトの作成

実習用のプロジェクトを作成する

- プロジェクトの種類はNew Projectか[**Quarto Project**]{.alert}
- プロジェクトを作る理由、方法は省略[（本講義の前提知識）]{.small}
- posit Cloudはそもそもプロジェクト単位で分析環境が管理されているため、不要[（というか自然にプロジェクトが作成される）]{.small}