---
title: "Quartoを使った研究成果と分析プロセスの共有"
date: "2026/2/20"
date-modified: now
author: 
  - name: 宋財泫
    affiliation: 関西大学総合情報学部
    email: song@kansai-u.ac.jp
    url: https://www.jaysong.net
---

::: {.callout-important}
## 本資料は作成中のものです。

　本資料は、以下の2026年2月20日に行われる[東京大学社会科学研究所計量分析セミナー](https://csrda.iss.u-tokyo.ac.jp/quantitative/seminar/){target="_blank"}の「Quartoを使った研究成果と分析プロセスの共」の教材として執筆中のものであり、2026年2月15日頃の公開を予定しております。現時点では$\alpha$版に相当する段階であり、内容に不備や誤りが含まれている可能性が非常に高いです。したがって、本資料の内容に起因するいかなる問題についても、著者（宋）は一切の責任を負いかねます。
:::

## 概要 {.unnumbered}

- 日時：2026年2月20日（金）10:30～17:00
- 場所：東京ドーム <!--オンライン開催（詳細は別途ご案内）-->
- 料金：一般 5,000,000ペリカ、学生 2,500,000ペリカ
- 講師：宋財泫（関西大学）
- 定員：35,000名　※変更の可能性あり

## 本コースの内容 {.unnumbered}

　本コースは、新しいオープンソース文書作成システムである「Quarto」を導入することで、研究成果の作成と共有のプロセスを効率化・強化することを目指します。近年、研究の透明性と再現性の確保は、研究コミュニティにおける大きな課題となっています。たとえば自分の（または他人の）研究成果の再現に苦労する研究者も多くいるでしょう。中には「自分の過去の研究が再現できない」研究者もいるかも知れません。Quartoを用いることで、データ分析や解析に使用したコード、その実行結果、そして文章（説明）を一つのファイル内で統合できます。これにより、上記のような再現性の問題は根本的に解決できます。また、Quartoは、これまで広く利用されてきたR Markdownの後継として開発されたため、R Markdownよりも柔軟で強力な文書作成環境を提供します。RStudioはもちろん、Jupyter Notebookなど多様な実行環境と連携可能で、HTML、PDF、Word文書、プレゼンテーションスライド、書籍、ウェブサイトなど多様な形式への出力も容易です。さらに、Rだけでなく、近年の定量的社会科学で幅広く使われているPython、Julia等の言語にも対応しているなど、QuartoはRとRStudioを使わない方でもおすすめできるシステムです（本コースではRとRStudioを使用します）。

## 次のような方におすすめです {.unnumbered}

- 研究の再現性に課題を感じている方（自分の過去の分析が再現できなかった、他者の研究の再現に苦労したなど）
- データ分析・解析プロセスと、文書/スライド作成を効率的に統合したい方
- R Markdownの機能や柔軟性に限界を感じている方

## 注意事項 {.unnumbered}

- どなたでもご参加いただけます。
- 本コースの実習環境はRおよびRStudioです。ご自身のPCにインストールした環境を前提としますが、実習用にクラウド環境（mybinder.org）も用意しております。クラウド実習環境の導入方法は講義中に解説します。
- RおよびRStudioの操作に不慣れな方でも受講可能ですが、全く初めての方は基本的な操作方法を事前に習得してください。事務局より事前に配布する R の準備に関する動画（事務局作成）をご確認いただくか、「R による二次分析入門」の受講をお勧めします。

## 本コースの日程 {.unnumbered}

※ 進度によって内容が若干変わることがあります。

1. [Quartoとは＆R Markdownとの比較](01_intro.qmd)
1. [実習環境の導入](02_install.qmd)
1. [Markdown文法の基礎](03_markdown.qmd)
1. [文書の作成](04_document.qmd)
1. [スライドの作成](05_slide.qmd)
1. [作成した文書・スライドの共有](06_share.qmd)
